M48
; DRILL file {KiCad 7.0.7} date Fri May 31 12:22:02 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-31T12:22:02-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.9307Y-3.8311
X4.9307Y-4.0587
T2
X4.8504Y-2.8819
X4.8504Y-4.9921
X7.1181Y-3.1339
X7.1181Y-4.9921
T0
M30
